#!/usr/bin/env php

<?php 

require_once __DIR__ . '/vendor/autoload.php'; 

use Symfony\Component\Console\Application; 
use DueDateCalculator\DueDateCalculatorCommand;

$app = new Application();
$app->add(new DueDateCalculatorCommand());
$app->run();